name: CI

on:
  push: {}
  pull_request: {}
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - run: zig fmt --check *.zig src/*.zig

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - uses: nektro/actions-setup-zigmod@v1

      - name: fetch dependencies
        run: zigmod fetch

      - name: Build examples
        run: zig build

      - name: Build and test
        run: zig build test
